### ISSUE TITLE
Add live digit update feature to calculator web app

### ISSUE THREAD

**Issue by samarthasthan** [tanmaysingh27/Calculator#1]
I would like to suggest adding a live digit update feature to the calculator web app. Currently, when a user inputs a calculation, they have to press the "equal" button to see the result. It would be much more user-friendly if the result was displayed as the user types, similar to how a physical calculator works.

**Comment by tanmaysingh27** [comment]
Solved the issue in below commit.
Thanks Smarth for advising the above change.

https://github.com/tanmaysingh27/Calculator/commit/ff01d97d855926631c30f14364b4793c7837eaa2
